USE [master]
GO

/****** Object:  Database [Tournaments]    Script Date: 2/5/2021 7:33:58 PM ******/
DROP DATABASE [Tournaments]
GO

/****** Object:  Database [Tournaments]    Script Date: 2/5/2021 7:33:58 PM ******/
CREATE DATABASE [Tournaments]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Tournaments', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\Tournaments.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Tournaments_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\Tournaments_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Tournaments].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Tournaments] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Tournaments] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Tournaments] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Tournaments] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Tournaments] SET ARITHABORT OFF 
GO

ALTER DATABASE [Tournaments] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [Tournaments] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Tournaments] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Tournaments] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Tournaments] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Tournaments] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Tournaments] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Tournaments] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Tournaments] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Tournaments] SET  ENABLE_BROKER 
GO

ALTER DATABASE [Tournaments] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Tournaments] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Tournaments] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Tournaments] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Tournaments] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Tournaments] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Tournaments] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Tournaments] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Tournaments] SET  MULTI_USER 
GO

ALTER DATABASE [Tournaments] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Tournaments] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Tournaments] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Tournaments] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Tournaments] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Tournaments] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Tournaments] SET  READ_WRITE 
GO

